name: "iits-chart-creator"
version: "0.1.6"
usage: "This creates helm charts based on iits standards"
description: "iits helm chart manager"
ignoreFlags: false
command: "$HELM_PLUGIN_DIR/iits-chart-creator"
platforms:
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    uri: https://github.com/iits-consulting/iits-chart-creator/releases/download/0.1.6/iits-chart-creator_0.1.6_darwin_amd64.tar.gz
    sha256: ""
  - selector:
      matchLabels:
        os: darwin
        arch: arm64
    uri: https://github.com/iits-consulting/iits-chart-creator/releases/download/0.1.6/iits-chart-creator_0.1.6_darwin_arm64.tar.gz
    sha256: ""
  - selector:
      matchLabels:
        os: linux
        arch: "386"
    uri: https://github.com/iits-consulting/iits-chart-creator/releases/download/0.1.6/iits-chart-creator_0.1.6_linux_386.tar.gz
    sha256: ""
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    uri: https://github.com/iits-consulting/iits-chart-creator/releases/download/0.1.6/iits-chart-creator_0.1.6_linux_amd64.tar.gz
    sha256: ""
  - selector:
      matchLabels:
        os: linux
        arch: arm64
    uri: https://github.com/iits-consulting/iits-chart-creator/releases/download/0.1.6/iits-chart-creator_0.1.6_linux_arm64.tar.gz
    sha256: ""
  - selector:
      matchLabels:
        os: windows
        arch: "386"
    uri: https://github.com/iits-consulting/iits-chart-creator/releases/download/0.1.6/iits-chart-creator_0.1.6_windows_386.tar.gz
    sha256: ""
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    uri: https://github.com/iits-consulting/iits-chart-creator/releases/download/0.1.6/iits-chart-creator_0.1.6_windows_amd64.tar.gz
    sha256: ""
  - selector:
      matchLabels:
        os: windows
        arch: arm64
    uri: https://github.com/iits-consulting/iits-chart-creator/releases/download/0.1.6/iits-chart-creator_0.1.6_windows_arm64.tar.gz
    sha256: ""