name: "iits-chart-creator"
version: "0.1.8"
usage: "This creates helm charts based on iits standards"
description: "iits helm chart manager"
ignoreFlags: false
command: "$HELM_PLUGIN_DIR/iits-chart-creator"
platformCommand:
  -  os: darwin
     arch: amd64
     command: "$HELM_PLUGIN_DIR/dist/iits-chart-creator_darwin_amd64_v1"
  -  os: darwin
     arch: arm64
     command: "$HELM_PLUGIN_DIR/dist/iits-chart-creator_darwin_arm64"
  -  os: linux
     arch: "386"
     command: "$HELM_PLUGIN_DIR/dist/iits-chart-creator_linux_386"
  -  os: linux
     arch: amd64
     command: "$HELM_PLUGIN_DIR/dist/iits-chart-creator_linux_amd64_v1"
  -  os: linux
     arch: arm64
     command: "$HELM_PLUGIN_DIR/dist/iits-chart-creator_linux_arm64"
  -  os: windows
     arch: "386"
     command: "$HELM_PLUGIN_DIR/dist/"
  -  os: windows
     arch: amd64
     command: "$HELM_PLUGIN_DIR/dist/"
  -  os: windows
     arch: arm64
     command: "$HELM_PLUGIN_DIR/dist/"