name: "iits-chart-creator"
version: "0.1.2"
usage: "This creates helm charts based on iits standards"
description: "iits helm chart manager"
ignoreFlags: false
command: "$HELM_PLUGIN_DIR/iits-chart-creator"
platforms:
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    uri: https://github.com/iits-consulting/iits-chart-creator/releases/download/0.1.2/iits-chart-creator-linux-amd64.tar.gz
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    uri: https://github.com/iits-consulting/iits-chart-creator/releases/download/0.1.2/iits-chart-creator-darwin-amd64.tar.gz
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    uri: https://github.com/iits-consulting/iits-chart-creator/releases/download/0.1.2/iits-chart-creator-windows-amd64.tar.gz


    iits-chart-creator_0.1.4_darwin_amd64.tar.gz
    iits-chart-creator_0.1.4_darwin_arm64.tar.gz
    iits-chart-creator_0.1.4_linux_386.tar.gz
    iits-chart-creator_0.1.4_linux_amd64.tar.gz
    iits-chart-creator_0.1.4_linux_arm64.tar.gz
    iits-chart-creator_0.1.4_windows_386.tar.gz
    iits-chart-creator_0.1.4_windows_amd64.tar.gz
    iits-chart-creator_0.1.4_windows_arm64.tar.gz