{{- if .Values.podMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "myService.fullname" $ }}
  {{- with .Values.podMonitor.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.podMonitor.annotations }}
  annotations:
    iits-consulting.chart-creator/version: CHART_CREATOR_VERSION
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "myService.selectorLabels" . | nindent 6 }}
  podMetricsEndpoints:
    - port: {{ default "metrics" .Values.podMonitor.port }}
      interval: {{ default "10s" .Values.podMonitor.interval }}
      path: {{ default "/metrics" .Values.podMonitor.path }}
{{- end }}