{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "myService.fullname" $ }}
  {{- with .Values.serviceMonitor.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.serviceMonitor.annotations }}
  annotations:
    iits-consulting.chart-creator/version: "1.0.2"
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "myService.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: {{ default "http" .Values.serviceMonitor.portName }}
      interval: {{ default "10s" .Values.serviceMonitor.interval }}
      path: {{ default "/metrics" .Values.serviceMonitor.path }}
{{- end }}