apiVersion: v1
kind: Service
metadata:
  name: {{ include "myService.fullname" . }}
  {{- with .annotations }}
  annotations:
    iits-consulting.chart-creator/version: CHART_CREATOR_VERSION
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
  labels:
    {{- include "myService.labels" . | nindent 4 }}
spec:
  type: {{ (.Values.service).serviceType | default "ClusterIP"}}
  ports:
    {{- range $name,$values := .Values.service.ports }}
    - targetPort: {{ ($values).targetPort | default 80 }}
      name: {{ ($values).name | default $name }}
      protocol: {{ ($values).protocol | default "TCP"}}
      port: {{($values).port | default 80 }}
    {{- end }}
  selector:
    {{- include "myService.selectorLabels" . | nindent 4 }}
