{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "myService.serviceAccountName" . }}
  labels:
    {{- include "myService.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    iits-consulting.chart-creator-version: "1.0.0"
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}