name: Build
on:
  pull_request:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
jobs:
  lint:
    name: Lint the iits-chart-creator source code
    runs-on: ubuntu-22.04
    steps:
      - name: Setup Go environment
        uses: actions/setup-go@v3
        with:
          go-version: ^1.20
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          github-token: ${{ secrets.GITHUB_TOKEN }}

  build:
    name: Build the iits-chart-creator
    runs-on: ubuntu-22.04
    steps:
      - name: Setup Go environment
        uses: actions/setup-go@v3
        with:
          go-version: ^1.20
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get dependencies
        run: |
          go get -v -t -d ./...
          if [ -f Gopkg.toml ]; then
              curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
              dep ensure
          fi
      - name: Build
        run: go build -v -o iits-chart-creator .
      - name: Upload the built binary executable for testing
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: iits-chart-creator

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: 'v3.7.1' # setup Helm version explicitly if necessary

      - name: Validate Helm Chart
        run: |
          helm template blueprints --set deployment.image.repository=myrepo --set deployment.image.tag=mytag