name: Build and Publish Artifacts

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GOOS: linux
      GOARCH: amd64
      BINARY_NAME_LINUX: iits-chart-creator-linux-amd64
      BINARY_NAME_DARWIN: iits-chart-creator-darwin-amd64
      BINARY_NAME_WINDOWS: iits-chart-creator-windows-amd64.exe

    steps:
      - uses: actions/checkout@v2
        name: Checkout code

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.20

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NOTARYTOOL_PASS: ${{ secrets.NOTARYTOOL_PASS }}

      - name: Update plugin.yaml
        run: |
          NEW_VERSION=${GITHUB_REF#refs/tags/}
          
          darwin_amd64_checksum=$(sha256sum dist/iits-chart-creator_${NEW_VERSION}_darwin_amd64.tar.gz | awk '{ print $1 }')
          darwin_arm64_checksum=$(sha256sum dist/iits-chart-creator_${NEW_VERSION}_darwin_arm64.tar.gz | awk '{ print $1 }')
          linux_386_checksum=$(sha256sum dist/iits-chart-creator_${NEW_VERSION}_linux_386.tar.gz | awk '{ print $1 }')
          linux_amd64_checksum=$(sha256sum dist/iits-chart-creator_${NEW_VERSION}_linux_amd64.tar.gz | awk '{ print $1 }')
          linux_arm64_checksum=$(sha256sum dist/iits-chart-creator_${NEW_VERSION}_linux_arm64.tar.gz | awk '{ print $1 }')
          windows_386_checksum=$(sha256sum dist/iits-chart-creator_${NEW_VERSION}_windows_386.tar.gz | awk '{ print $1 }')
          windows_amd64_checksum=$(sha256sum dist/iits-chart-creator_${NEW_VERSION}_windows_amd64.tar.gz | awk '{ print $1 }')
          windows_arm64_checksum=$(sha256sum dist/iits-chart-creator_${NEW_VERSION}_windows_arm64.tar.gz | awk '{ print $1 }')
          
          
          cp plugin_template.yaml plugin.yaml
          sed -i -e "s/NEW_VERSION/$NEW_VERSION/g" \
                 -e "s/darwin_amd64_checksum/$darwin_amd64_checksum/g" \
                 -e "s/darwin_arm64_checksum/$darwin_arm64_checksum/g" \
                 -e "s/linux_386_checksum/$linux_386_checksum/g" \
                 -e "s/linux_amd64_checksum/$linux_amd64_checksum/g" \
                 -e "s/linux_arm64_checksum/$linux_arm64_checksum/g" \
                 -e "s/windows_386_checksum/$windows_386_checksum/g" \
                 -e "s/windows_amd64_checksum/$windows_amd64_checksum/g" \
                 -e "s/windows_arm64_checksum/$windows_arm64_checksum/g" plugin.yaml 

      - name: Commit and Push new plugin.yaml
        run: |
          git config --global user.name 'iits'
          git config --global user.email 'cloudOps@iits-consulting.de'
          git add plugin.yaml
          git commit -m "Update plugin.yaml with new version and checksums"
          git push origin HEAD:main