name: Build and Publish Artifacts

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build Go project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16     # Set a minimum Go version, adjust as necessary

      - name: Get dependencies
        run: go mod download

      - name: Build Linux binary
        env:
          GOOS: linux
          GOARCH: amd64
        run: go build -v -o iits-chart-creator-linux-amd64

      - name: Build macOS binary
        env:
          GOOS: darwin
          GOARCH: amd64
        run: go build -v -o iits-chart-creator-darwin-amd64

      - name: Build Windows binary
        env:
          GOOS: windows
          GOARCH: amd64
        run: go build -v -o iits-chart-creator-windows-amd64.exe

      - name: Update plugin.yaml
        run: |
          NEW_VERSION=${GITHUB_REF#refs/tags/}
          LINUX_CHECKSUM=$(sha256sum iits-chart-creator-linux-amd64 | awk '{ print $1 }')
          DARWIN_CHECKSUM=$(sha256sum iits-chart-creator-darwin-amd64 | awk '{ print $1 }')
          WINDOWS_CHECKSUM=$(sha256sum iits-chart-creator-windows-amd64.exe | awk '{ print $1 }')
          
          cp plugin_template.yaml plugin.yaml
          sed -i -e "s/NEW_VERSION/$NEW_VERSION/g" -e "s/LINUX_CHECKSUM/$LINUX_CHECKSUM/g" -e "s/DARWIN_CHECKSUM/$DARWIN_CHECKSUM/g" -e "s/WINDOWS_CHECKSUM/$WINDOWS_CHECKSUM/g" plugin.yaml 

      - name: Upload Linux binary to artifacts
        uses: actions/upload-artifact@v2
        with:
          name: iits-chart-creator-linux-amd64
          path: iits-chart-creator-linux-amd64

      - name: Upload macOS binary to artifacts
        uses: actions/upload-artifact@v2
        with:
          name: iits-chart-creator-darwin-amd64
          path: iits-chart-creator-darwin-amd64

      - name: Upload Windows binary to artifacts
        uses: actions/upload-artifact@v2
        with:
          name: iits-chart-creator-windows-amd64
          path: iits-chart-creator-windows-amd64.exe