name: Build and Publish Artifacts

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GOOS: linux
      GOARCH: amd64
      BINARY_NAME_LINUX: iits-chart-creator-linux-amd64
      BINARY_NAME_DARWIN: iits-chart-creator-darwin-amd64
      BINARY_NAME_WINDOWS: iits-chart-creator-windows-amd64.exe

    steps:
      - uses: actions/checkout@v2
        name: Checkout code

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.20

      - name: Replace version in Go file
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          sed -i "s/{Version}/$VERSION/g" main.go

      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          install-only: true

      - name: Build with GoReleaser
        run: goreleaser build

      - name: Update plugin.yaml
        run: |
          NEW_VERSION=${GITHUB_REF#refs/tags/}
          cp plugin_template.yaml plugin.yaml
          sed -i -e "s/NEW_VERSION/$NEW_VERSION/g" plugin.yaml 

      - name: Commit and Push new plugin.yaml
        run: |
          git config --global user.name 'iits'
          git config --global user.email 'cloudOps@iits-consulting.de'
          git add plugin.yaml
          cp -R dist/iits-chart-creator_* binaries/
          git add binaries/iits-chart-creator_*
          git commit -m "Update plugin.yaml with new version and binaries"
          git push origin HEAD:main